-- 069: Seed the 5 public-domain original gallery designs generated 2026-10-08.
-- Book Winnie the Pooh (1926), Norse Thor, Norse Loki (trio, commit af8f2bc)
-- plus book Tigger (1928) and Peter Rabbit (1902) (duo, commit 0a1ee3f).
-- Owner standing rule 2026-10-08: public-domain versions go in the MAIN GALLERY
-- as original art; copyrighted studio versions stay by-request only.
-- Idempotent: ON CONFLICT (id) DO NOTHING, safe to re-run.
-- NOTE: no trailing-semicolon comments (migrate.js splits on semicolon lines)
INSERT INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('pd-winnie-the-pooh', 'Winnie the Pooh', 'Original public-domain storybook teddy bear tattoo design (A.A. Milne 1926 book version, NOT Disney). Full color with shading plus matching clean linework included.', '["Fairy Tale & Storybook","Winnie the Pooh"]', 'designs/color-clean/winnie-the-pooh.jpg', 'designs/linework-clean/winnie-the-pooh.jpg', '/img/designs/winnie-the-pooh.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791564000000, 0, 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('pd-thor-norse', 'Thor, God of Thunder', 'Original Norse god of thunder tattoo design - Viking warrior with braided beard and war hammer Mjolnir (NOT Marvel). Full color with shading plus matching clean linework included.', '["Mythology & Fantasy","Thor, God of Thunder"]', 'designs/color-clean/thor-norse.jpg', 'designs/linework-clean/thor-norse.jpg', '/img/designs/thor-norse.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791564000000, 0, 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('pd-loki-norse', 'Loki, Trickster God', 'Original Norse trickster god tattoo design - slender cunning Viking figure (NOT Marvel). Clean linework edition (color version to follow).', '["Mythology & Fantasy","Loki, Trickster God"]', '', 'designs/linework-clean/loki-norse.jpg', '/img/designs/loki-norse.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791564000000, 0, 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('tigger-book', 'Tigger', 'Original storybook-style tattoo design of Tigger (A.A. Milne''s 1928 book version, public domain - NOT Disney) bouncing on his springy tail. Full color with shading plus matching clean linework included.', '["Classic Tales","Tigger"]', 'designs/color/tigger-book-color.jpg', 'designs/linework-clean/tigger-book-linework.jpg', '/img/designs/tigger-book-linework-wm.jpg', 7500, NULL, 'approved', 'gallery', 'Storybook', 1791564000000, 0, 0, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('peter-rabbit', 'Peter Rabbit', 'Original tattoo-style rendition of Peter Rabbit (Beatrix Potter''s 1902 character, public domain), the mischievous rabbit in his blue jacket. Full color with shading plus matching clean linework included.', '["Classic Tales","Peter Rabbit"]', 'designs/color/peter-rabbit-color.jpg', 'designs/linework-clean/peter-rabbit-linework.jpg', '/img/designs/peter-rabbit-linework-wm.jpg', 7500, NULL, 'approved', 'gallery', 'Storybook', 1791564000000, 0, 0, NULL) ON CONFLICT (id) DO NOTHING;
