-- 078: Seed the 9 nightly original gallery designs generated 2026-10-08.
-- These are all original art (no copyrighted characters, no fan art) from the
-- nightly category gap-fill batch (9 random empty categories, one design each).
-- Owner standing rule: original designs go in the MAIN GALLERY.
-- Idempotent: INSERT OR IGNORE, safe to re-run.
-- NOTE: no trailing-semicolon comments (migrate.js splits on semicolon lines)
INSERT OR IGNORE INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('nightly-time-clocks', 'Clockwork Heart', 'Original tattoo design "Clockwork Heart" - a heart-shaped vintage pocket watch with exposed gears. Full color with shading plus matching clean linework included.', '["Time / Clocks"]', 'designs/color/nightly-time-clocks.jpg', 'designs/linework-clean/nightly-time-clocks.jpg', '/img/designs/nightly-time-clocks.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791587241000, 0, 0, NULL);
INSERT OR IGNORE INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('nightly-sci-fi', 'Neon Drifter', 'Original tattoo design "Neon Drifter" - a futuristic astronaut floating among the stars. Full color with shading plus matching clean linework included.', '["Sci-Fi / Futuristic"]', 'designs/color/nightly-sci-fi.jpg', 'designs/linework-clean/nightly-sci-fi.jpg', '/img/designs/nightly-sci-fi.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791587241000, 0, 0, NULL);
INSERT OR IGNORE INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('nightly-surreal', 'The Watcher', 'Original tattoo design "The Watcher" - a giant eye over a surreal floating dreamscape. Full color with shading plus matching clean linework included.', '["Surreal / Bizarre"]', 'designs/color/nightly-surreal.jpg', 'designs/linework-clean/nightly-surreal.jpg', '/img/designs/nightly-surreal.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791587241000, 0, 0, NULL);
INSERT OR IGNORE INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('nightly-zodiac', 'Celestial Wheel', 'Original tattoo design "Celestial Wheel" - an ornate zodiac wheel with constellations, sun and moon. Full color with shading plus matching clean linework included.', '["Zodiac / Astrology"]', 'designs/color/nightly-zodiac.jpg', 'designs/linework-clean/nightly-zodiac.jpg', '/img/designs/nightly-zodiac.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791587241000, 0, 0, NULL);
INSERT OR IGNORE INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('nightly-tattoo-styles', 'Heritage Flash', 'Original tattoo design "Heritage Flash" - classic American traditional rose, dagger and swallow composition. Full color with shading plus matching clean linework included.', '["Tattoo Styles"]', 'designs/color/nightly-tattoo-styles.jpg', 'designs/linework-clean/nightly-tattoo-styles.jpg', '/img/designs/nightly-tattoo-styles.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791587241000, 0, 0, NULL);
INSERT OR IGNORE INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('nightly-western', 'Desert Outlaw', 'Original tattoo design "Desert Outlaw" - a cowboy skull with desert frontier scene. Full color with shading plus matching clean linework included.', '["Western"]', 'designs/color/nightly-western.jpg', 'designs/linework-clean/nightly-western.jpg', '/img/designs/nightly-western.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791587241000, 0, 0, NULL);
INSERT OR IGNORE INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('nightly-vehicles', 'Iron Stallion', 'Original tattoo design "Iron Stallion" - a vintage chopper motorcycle with flame details. Full color with shading plus matching clean linework included.', '["Vehicles"]', 'designs/color/nightly-vehicles.jpg', 'designs/linework-clean/nightly-vehicles.jpg', '/img/designs/nightly-vehicles.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791587241000, 0, 0, NULL);
INSERT OR IGNORE INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('nightly-wings', 'Ascension', 'Original tattoo design "Ascension" - majestic angel wings spread wide with detailed feathers. Full color with shading plus matching clean linework included.', '["Wings"]', 'designs/color/nightly-wings.jpg', 'designs/linework-clean/nightly-wings.jpg', '/img/designs/nightly-wings.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791587241000, 0, 0, NULL);
INSERT OR IGNORE INTO designs (id, title, description, categories, color_path, linework_path, linework_wm_path, price_cents, artist_id, status, listing_scope, style, created_at, sale_count, show_featured, show_air_at) VALUES ('nightly-steampunk', 'Brass Aviator', 'Original tattoo design "Brass Aviator" - a Victorian steampunk airship with gears and brass fittings. Full color with shading plus matching clean linework included.', '["Steampunk"]', 'designs/color/nightly-steampunk.jpg', 'designs/linework-clean/nightly-steampunk.jpg', '/img/designs/nightly-steampunk.jpg', 7500, NULL, 'approved', 'gallery', 'Original', 1791587241000, 0, 0, NULL);
